/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hellofx;

import javafx.application.Application;

public class MainApp {

    public static void main(String[] args) {
        System.out.println("Starting");
        Application.launch(MainCalculatorWindow.class, args);
    }

}
